# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            geist
tagline:          'Augmenting the Embodied Mind'
description:      'Augmenting the Embodied Mind'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Kai Kunze'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
