# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            geist
tagline:          'Augmenting the Embodied Mind'
description:      'Augmenting the Embodied Mind'
url:              http://geist.pro/
baseurl:          /

author:
  name:           'Kai Kunze'
  url:            https://twitter.com/k_garten

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/k_kai

portfolio_dir: "projects"

related_project_keys: ["category", "technology"]

related_min_common: 0.7
